Xfel merge filter by resolution n obs
cctbx/cctbx_project pull request #1030
Opened 2024-12-02 15:36 UTC by dwmoreau

Implemented experiment filters by resolution and number of observations within cctbx.xfel.merge

2024-12-03 17:54 UTC, phyy-nx requested changes
Looks like a good feature.  Some review comments added.

2024-12-03 17:54 UTC, phyy-nx commented on xfel/merging/application/filter/experiment_filter.py
> +    if (not filter_by_unit_cell) and (not filter_by_n_obs) and (not filter_by_resolution):
These validation steps should likely be in the validate function.  validate runs before the program starts execution, which will save time if the parameters are invalid.

2024-12-03 17:54 UTC, phyy-nx commented on xfel/merging/application/phil/phil.py
>      .multiple = True
If .type = choice and .multiple = true, then params.filter.algorithm should be a list of already validated strings.  Is there a reason that doesn't work?

2024-12-03 17:54 UTC, phyy-nx commented on xfel/merging/application/filter/experiment_filter.py
> +    data_counter(self.params).count(new_experiments, new_reflections)
data_counter result not checked?

2024-12-03 17:54 UTC, phyy-nx commented on xfel/merging/application/phil/phil.py
> +  .help = only unit_cell, resolution, and n_obs are implemented
Let's go ahead and drop reindex and report if they aren't implemented.

2025-01-08 18:48 UTC, dwmoreau commented on xfel/merging/application/phil/phil.py
> +  .help = only unit_cell, resolution, and n_obs are implemented
reindex and report have been removed from the phil file and experiment_filter.py

2025-01-08 18:50 UTC, dwmoreau commented on xfel/merging/application/filter/experiment_filter.py
> +    data_counter(self.params).count(new_experiments, new_reflections)
The problem was that with multiple filters, each filter can flag the same experiment. I use a list(set()) operation to get the unique experiment id's and use the length of this list to get the number of unique experiments that are removed.

2025-01-08 18:52 UTC, dwmoreau commented on xfel/merging/application/filter/experiment_filter.py
> +    if (not filter_by_unit_cell) and (not filter_by_n_obs) and (not filter_by_resolution):
I moved these into the validate method. If the validation fails because:

- No algorithm in the algorithms list: the original experiments and reflections are returned.
- Error in input parameters: assertion fail.

2025-01-15 19:38 UTC, dwmoreau commented
Test failures unrelated to feature.

2025-01-15 19:38 UTC, merged