Remove redundant libtbx Python 3 syntax check test
cctbx/cctbx_project pull request #527
Opened 2020-09-16 15:31 UTC by Anthchirp

Thanks to @bkpoon this is now covered by a Microsoft Azure test, which covers more code than just libtbx, is platform-agnostic, runs directly on any commit, has its own (up-to-date) exception list, and thus provides much more useful feedback.

We should therefore remove this from libtbx.

2020-09-18 22:54 UTC, Anthchirp commented
Syntax checks are only failing due to unrelated mmtbx stuff.

2020-09-19 00:05 UTC, bkpoon requested changes
Please remove some extra cruft. Thanks!

2020-09-19 00:05 UTC, bkpoon commented on libtbx/run_tests.py
>  # failing tests on Windows, Python 3
This whole section can be removed.
```
# failing tests on Windows, Python 3
tst_list_windows_fail_py3 = [
]
if sys.platform == 'win32' and sys.version_info[0] > 2:
  tst_list_fail += tst_list_windows_fail_py3
else:
  tst_list_base += tst_list_windows_fail_py3
```

2020-09-20 00:45 UTC, bkpoon commented
/azp run

2020-09-20 12:37 UTC, Anthchirp commented
Test failures are unrelated (and fixed on master) → merging.

2020-09-20 12:37 UTC, merged