Detect gpu architecture for kokkos
cctbx/cctbx_project pull request #650
Opened 2021-09-01 20:44 UTC by Trzs

Change SConscript to look for available (Nvidia) GPUs. If no Nvidia gpu is found, Intel Haswell architecture is assumed. The possible GPUs are V100 and A100.

2021-09-01 22:18 UTC, JBlaschke requested changes

2021-09-01 22:18 UTC, JBlaschke commented on simtbx/kokkos/SConscript
> +  if verbal:
`verbal` => `verbose`?

2021-09-01 23:15 UTC, Trzs commented on simtbx/kokkos/SConscript
> +  if verbal:
good catch

2021-09-01 23:59 UTC, nksauter approved these changes

2021-09-02 05:24 UTC, bkpoon approved these changes

2021-09-02 05:26 UTC, merged